---
abstract: 'Perl interface to Google Reader'
author:
  - 'gray <gray@cpan.org>'
build_requires:
  Test::More: 0.82
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112600'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Google-Reader
no_index:
  directory:
    - t
    - inc
recommends:
  JSON::XS: 2
requires:
  Class::Accessor::Fast: 0
  Encode: 0
  HTTP::Request::Common: 0
  JSON: 2
  LWP::Protocol::https: 6.02
  LWP::UserAgent: 6.02
  URI: 1.36
  URI::Escape: 0
  URI::QueryParam: 0
  XML::Atom: 0
  XML::LibXML: 0
  parent: 0
resources:
  repository: http://github.com/gray/webservice-google-reader
version: 0.20
