--- #YAML:1.0
name:                WebService-Google-Reader
version:             0.01_2
abstract:            Perl interface for Google Reader
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0
    JSON::Any:                     0
    LWP::UserAgent:                0
    Test::More:                    0
    XML::Atom:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - gray <gray@cpan.org>
