--- #YAML:1.0
name:               WebService-Google-Reader
version:            0.17
abstract:           Perl interface to Google Reader
author:
    - gray <gray@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.82
requires:
    Class::Accessor::Fast:  0
    Encode:               0
    HTTP::Cookies:        0
    HTTP::Request::Common:  0
    JSON:                 2
    LWP::Protocol::https:  6.02
    LWP::UserAgent:       6.02
    parent:               0
    URI:                  1.36
    URI::Escape:          0
    URI::QueryParam:      0
    XML::Atom:            0
    XML::LibXML:          0
resources:
    repository:  http://github.com/gray/webservice-google-reader
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    JSON::XS:  2
